### PR TITLE
updated MSYFitbit.swift code to swift 3

### PR DESCRIPTION
**Pull request by paulsumit1993**
updated the file to work with Xcode 8 beta 6 and Swift 3.

### CODE REVIEW

**Comment by paulsumit1993** [comment]
please update the OAuthSwift library from https://github.com/OAuthSwift/OAuthSwift/tree/swift3.0 for this file to work.

**Comment by paulsumit1993** [comment]
[OAuthSwift.zip](https://github.com/msyshani/FitBit-Auth-for-iOS/files/426971/OAuthSwift.zip)

**Comment by cwinUser** [comment]
@paulsumit1993 hello , but that  OAuthSwift library is not working even pod is not getting installed it is giving error [!] Unable to find a specification for `FitBit_iOS`
 .. n shared above link  https://github.com/OAuthSwift/OAuthSwift/tree/swift3.0  shows page not found. Can u please help mi or fix issue to work with that library in swift 3?

**Comment by paulsumit1993** [comment]
Just use the latest swift Oauth library https://github.com/OAuthSwift/OAuthSwift and use the updated MSYFitbit.swift file for fetching data from Fitbit servers

**Comment by paulsumit1993** [comment]
This library is no longer maintained I think

**Pull request closed without merging**
